In [1]:
import numpy as np
import pandas as pd
from NeuronHandler import Neuron
from matplotlib import pyplot as plt

### Задание 1
С помощью функции ReLU разделить данные XOR

***Решением будет:***
Ответ функции ReLU ==> 0, если это (1, 1)/(0, 0); и 1, если это (0, 1)/(1, 0)
(0, 0) -> любые веса;
(1, 1) -> только отрицательные
(0, 1) -> только положительные
(1, 0) -> только положительные

In [59]:
ns = [Neuron(i) for i in range(4)]
rate = 0.1

xs = pd.DataFrame([(0, 0), (1, 1), (1, 0), (0, 1)])
xs_labels = pd.Series([0, 0, 1, 1])
ws = pd.DataFrame([[np.random.uniform(0, 1) for i in range(len(ns))], [np.random.uniform(0, 1) for i in range(len(ns))]]).T

ws.iloc[1] = ws.iloc[1] * (-1)

In [60]:
ws

0         1
0  0.903987  0.472355
1 -0.735021 -0.743566
2  0.399061  0.107394
3  0.392035  0.999866

In [61]:
xs

0  1
0  0  0
1  1  1
2  1  0
3  0  1

In [62]:
data = []
for i in range(xs.index.size):  # iter for samples
    data.append(ns[i].relu(xs, ws, i))

print(data)
for i in range(len(data)):
    if data[i] > 0:
        data[i] = 1

print(data, xs_labels.values)

[0, 0, 0.39906050883914623, 0.999866107262478]
[0, 0, 1, 1] [0 0 1 1]


### Задание 2
Даны двумерные данные, точка х1 и х2, помеченные как x1 > x2 (Positive class), x1 < x2 (Negative class).

**ПУНКТ -- А** <font color='green'>**(X)**</font> <font color='green'>**(X)**</font> <font color='green'>**(X)**</font> <font color='green'>**(X)**</font>
1) Создать 20 тренировочных данных в положительном квадранте единичного квадрата <font color='green'>**(X)**</font>
2) Написать алгоритм персептрона классифицирующий эти данные и обучить его на тренировочной выборке <font color='green'>**(X)**</font>
3) Сгенерировать 1000 тест-данных <font color='green'>**(X)**</font>
4) Получить данные статистики об этом алгоритме <font color='green'>**(X)**</font>

**ПУНКТ -- Б** <font color='green'>**(X)**</font> <font color='green'>**(X)**</font>
1) Заменить нейрон на модель Адалайн <font color='green'>**(X)**</font>
2) Провести аналогичные подсчеты статистики <font color='green'>**(X)**</font>

In [3]:
from Perceptron import Percept

In [22]:
x1 = np.array([np.random.uniform(0, 1) for i in range(20)])
x2 = np.array([np.random.uniform(0, 1) for i in range(20)])
y = np.array(x1 > x2)
X = pd.DataFrame([x1, x2]).T
X

0         1
0   0.677168  0.123130
1   0.680913  0.485076
2   0.722987  0.714899
3   0.127287  0.194355
4   0.544868  0.687697
5   0.733985  0.382713
6   0.761930  0.498311
7   0.187895  0.650165
8   0.318097  0.823536
9   0.304565  0.903373
10  0.235444  0.140343
11  0.440557  0.800028
12  0.066672  0.903006
13  0.320971  0.370086
14  0.961189  0.141066
15  0.517517  0.091413
16  0.150238  0.699969
17  0.653962  0.775964
18  0.424924  0.053296
19  0.693557  0.712884

In [10]:
y

array([ True,  True, False, False,  True, False,  True, False,  True,
       False,  True, False,  True,  True, False,  True, False, False,
       False,  True])

In [11]:
perceptron = Percept(X, y, amount_of_hidden_neurons=25)

In [12]:
perceptron.transform_fit(epochs=10)
print("Precision:", perceptron.precision, "\nRecall:", perceptron.recall, "\nMean harmonic:", perceptron.f1_score)

Epoch# 1 / 10
Epoch# 2 / 10
Epoch# 3 / 10
Epoch# 4 / 10
Epoch# 5 / 10
Epoch# 6 / 10
Epoch# 7 / 10
Epoch# 8 / 10
Epoch# 9 / 10
Epoch# 10 / 10
1.3983113765716553 sec
Precision: 0.4 
Recall: 0.4 
Mean harmonic: 0.4000000000000001


In [13]:
y

array([ True,  True, False, False,  True, False,  True, False,  True,
       False,  True, False,  True,  True, False,  True, False, False,
       False,  True])

In [14]:
for x in X.values:
    print(perceptron.predict(x))

True
False
True
True
False
True
False
False
True
True
False
True
False
True
True
True
False
False
False
False


In [15]:
x1_test = np.array([np.random.uniform(0, 1) for i in range(1000)])
x2_test = np.array([np.random.uniform(0, 1) for i in range(1000)])
y_test = np.array(x1_test > x2_test)
X_test = pd.DataFrame([x1_test, x2_test]).T
X_test

0         1
0    0.946424  0.981756
1    0.071421  0.654798
2    0.725989  0.745029
3    0.137162  0.083606
4    0.016508  0.522729
..        ...       ...
995  0.457399  0.134340
996  0.136180  0.293701
997  0.373653  0.239041
998  0.695899  0.490255
999  0.372353  0.206267

[1000 rows x 2 columns]

In [16]:
y_test_estimating = [perceptron.predict(x) for x in X_test.values]
y_test_estimating

[False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,

### Пояснение:
При малом количестве эпох, модель не успевает переобучится и показывает периодические совпадения, однако они далеко не идеальны.

In [17]:
TP = 0
TN = 0
FP = 0
FN = 0
precision = None
recall = None
f1_score = None
l = np.where(y_test, 1, 0)
p = np.where(y_test_estimating, 1, 0)
l_plus_p = l+p
l_minus_p = l-p
for i in range(len(l_plus_p)):
    if l_plus_p[i] == 2:
        TP += 1
    elif l_plus_p[i] == 0:
        TN += 1
    elif l_minus_p[i] == -1:
        FP += 1
    elif l_minus_p[i] == 1:
        FN += 1

precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * precision * recall / (precision + recall)

print("Precision:", perceptron.precision, "\nRecall:", perceptron.recall, "\nMean harmonic:", perceptron.f1_score)

Precision: 0.4 
Recall: 0.4 
Mean harmonic: 0.4000000000000001


### Пояснение:
При большом количестве эпох обучения модель невозможно обобщить на тест-данных.

**Проблемы:**
- Малое количество обучающих выборок
- Модель невозможно обобщить
- Переобучение на обучающем наборе

In [19]:
perceptron = Percept(X, y, amount_of_hidden_neurons=100)
perceptron.transform_fit(epochs=120)
print("Precision:", perceptron.precision, "\nRecall:", perceptron.recall, "\nMean harmonic:", perceptron.f1_score)

Epoch# 1 / 120
Epoch# 2 / 120
Epoch# 3 / 120
Epoch# 4 / 120
Epoch# 5 / 120
Epoch# 6 / 120
Epoch# 7 / 120
Epoch# 8 / 120
Epoch# 9 / 120
Epoch# 10 / 120
Epoch# 11 / 120
Epoch# 12 / 120
Epoch# 13 / 120
Epoch# 14 / 120
Epoch# 15 / 120
Epoch# 16 / 120
Epoch# 17 / 120
Epoch# 18 / 120
Epoch# 19 / 120
Epoch# 20 / 120
Epoch# 21 / 120
Epoch# 22 / 120
Epoch# 23 / 120
Epoch# 24 / 120
Epoch# 25 / 120
Epoch# 26 / 120
Epoch# 27 / 120
Epoch# 28 / 120
Epoch# 29 / 120
Epoch# 30 / 120
Epoch# 31 / 120
Epoch# 32 / 120
Epoch# 33 / 120
Epoch# 34 / 120
Epoch# 35 / 120
Epoch# 36 / 120
Epoch# 37 / 120
Epoch# 38 / 120
Epoch# 39 / 120
Epoch# 40 / 120
Epoch# 41 / 120
Epoch# 42 / 120
Epoch# 43 / 120
Epoch# 44 / 120
Epoch# 45 / 120
Epoch# 46 / 120
Epoch# 47 / 120
Epoch# 48 / 120
Epoch# 49 / 120
Epoch# 50 / 120
Epoch# 51 / 120
Epoch# 52 / 120
Epoch# 53 / 120
Epoch# 54 / 120
Epoch# 55 / 120
Epoch# 56 / 120
Epoch# 57 / 120
Epoch# 58 / 120
Epoch# 59 / 120
Epoch# 60 / 120
Epoch# 61 / 120
Epoch# 62 / 120
Epoch# 63 / 120
E

In [6]:
x1 = np.array([np.random.uniform(0, 1) for i in range(20)])
x2 = np.array([np.random.uniform(0, 1) for i in range(20)])
y = np.array(x1 > x2)
X = pd.DataFrame([x1, x2]).T

perceptron = Percept(X, y, amount_of_hidden_neurons=70, is_ADLiNE=True)
perceptron.transform_fit(epochs=10)
print("Precision:", perceptron.precision, "\nRecall:", perceptron.recall, "\nMean harmonic:", perceptron.f1_score)

Epoch# 1 / 10
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
Epoch# 2 / 10
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
Epoch# 3 / 10
[1]
[-1]
[1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]


D:\Repositories\application_of_neural_network_algorithms\task2_(Classifier)\Perceptron.py:174: RuntimeWarning: overflow encountered in scalar multiply
  self.local_gradient = error * self.__derivative_of_signum(self.last_indu_field)
D:\Repositories\application_of_neural_network_algorithms\task2_(Classifier)\Perceptron.py:139: RuntimeWarning: invalid value encountered in scalar add
  return weight + delta_w


[1]
[-1]
[1]
[-1]
[1]
[-1]
Epoch# 4 / 10
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[1]
[-1]
Epoch# 5 / 10
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
Epoch# 6 / 10
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
Epoch# 7 / 10
[1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
Epoch# 8 / 10
[1]
[-1]
[1]
[-1]
[1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
Epoch# 9 / 10
[-1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
Epoch# 10 / 10
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[1]
[-1]
[1]
[-1]
[1]
[-1]
[1]
[0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 
 [1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2] [-1 -1  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
6 0 14 0
2.0266525745391846 sec
Precision: 0.3 
Recall: 1.0 
Mean

## Ответ:
В итоге получили незначительные отклонения без/c Adaptive Linear Neuron

### Задание 3
Написать персептрон с обучением в виде обратного распространения.
Классифицировать карты 3х3 содержащие буквы: X, Y, L, I

In [2]:
import PerceptronIMGS

In [3]:
x1 = np.array([1,0,1,0,1,0,1,0,1])  # X
x2 = np.array([1,0,1,0,1,0,0,1,0])  # Y
x3 = np.array([0,1,0,0,1,0,0,1,0])  # I
x4 = np.array([1,0,0,1,0,0,1,1,1])  # L
y1 = np.array([1,0,0,0])  # X
y2 = np.array([0,1,0,0])  # Y
y3 = np.array([0,0,1,0])  # I
y4 = np.array([0,0,0,1])  # L
X = pd.DataFrame([x1, x2, x3, x4])
y = pd.DataFrame([y1, y2, y3, y4])
perceptron = PerceptronIMGS.PerceptIMGS(X, y, amount_of_hidden_neurons=150)

In [4]:
perceptron.transform_fit(epochs=1000)

Epoch# 1 / 1000
[0.9603450122331544, 0.006972472784691903, 0.01044325115130686, 0.00014879947414980926] 

[0.2577074574473172, 0.010609043231961334, 0.018751945997062917, 0.10654474333859] 

[9.367803274282498e-05, 0.01620098443095162, 0.19079592147257618, 0.14911946741300863] 

[0.019582762676677645, 0.03605543703614808, 8.903464176559428e-05, 0.9467517286794627] 

Epoch# 2 / 1000
[0.00010218542175670386, 0.015952739799630623, 0.1620942141793929, 0.22805330721999054] 

[0.9411624817711155, 0.007246849366759048, 0.008885472167839198, 0.0003431636866512622] 

[0.1742645764839864, 0.01123380171687998, 0.015420246383001037, 0.22321511811975656] 

[0.01563262741870861, 0.03742565935902733, 8.25466275041057e-05, 0.9551299599604696] 

Epoch# 3 / 1000
[0.16570834043682797, 0.011741413578779152, 0.015482229357332275, 0.1486609308135958] 

[0.015753957189053144, 0.038760717797851736, 8.275957586775264e-05, 0.9335460288054519] 

[7.578754940587167e-05, 0.017178340518466194, 0.14802682051554356, 

In [5]:
perceptron.predict([1,0,1,0,1,0,1,0,1])  # X

0    0.975225
1    0.019154
2    0.000024
3    0.011929
dtype: float64

In [6]:
perceptron.predict([1, 1, 1, 0, 1, 0, 1, 0, 1])  # X + white_noise

0    0.991218
1    0.000177
2    0.000164
3    0.000217
dtype: float64

In [7]:
perceptron.predict([0,1,0,0,1,0,0,1,0])  # I

0    0.011566
1    0.018212
2    0.978121
3    0.000176
dtype: float64

In [8]:
perceptron.predict([1,1,0,0,1,0,0,1,0])  # I + white_noise

0    0.001994
1    0.091218
2    0.555334
3    0.000286
dtype: float64